import React, { useState } from 'react'
import utility from '../utils/CapApiUtils'

// let qlik;
// let { qlik } = utility.qlobals;
let capabilityApisPromise
let capApiSAASPromise

const _deserialize = response => (response.status !== 200 ? false : response.json())

function getTenant() {
  return _request('/api/v1/tenants/me').then(_deserialize);
}

function getUser() {
  return _request('/api/v1/users/me').then(_deserialize);
}

function _request(url, config, method = 'GET', payload = null) {
  if (config) {
    const tenantUrl = config.host
    const webIntegrationId = config.webIntId

    return fetch(`https://${tenantUrl}${url}`, {
      method,
      mode: 'cors', // cors must be enabled
      credentials: 'include', // credentials must be included
      headers: {
        'Content-Type': 'application/json',
        'qlik-web-integration-id': webIntegrationId, // needed in order to whitelist your domain
      },
      body: payload,
    })
  }
}

const loadCapSAAS = async config => {
  try {
    if (capApiSAASPromise) {
      await capApiSAASPromise

      return
    }
    const tenantUrl = config.host
    const webIntegrationId = config.webIntId

    const link = document.createElement('link')
    link.rel = 'stylesheet'
    link.href = `https://${tenantUrl}/resources/autogenerated/qlik-styles.css`
    document.head.appendChild(link)
    link.loaded = new Promise(resolve => {
      link.onload = () => { resolve() }
    })

    const script = document.createElement('script')
    script.src = `https://${tenantUrl}/resources/assets/external/requirejs/require.js`
    script.onload = async () => {
      window.require.config({
        baseUrl: `https://${tenantUrl}/resources`,
        webIntegrationId,
      })
    }

    script.loaded = new Promise(resolve => {
      script.onload = () => { resolve() }
    })

    document.body.appendChild(script)

    capApiSAASPromise = Promise.all([link.loaded, script.loaded])
    await capApiSAASPromise
  
  } catch (error) {
    throw new Error(error)
  }
}

const loadCapabilityApis = async config => {
  try {
    if (capabilityApisPromise) {
      await capabilityApisPromise

      return
    }
    const capabilityApisJS = document.createElement('script')
    const prefix = (config.prefix !== '') ? `/${config.prefix}` : ''
    capabilityApisJS.src = `${(config.secure ? 'https://' : 'http://') + config.host + (config.port ? `:${config.port}` : '') + prefix}/resources/assets/external/requirejs/require.js`
    document.head.appendChild(capabilityApisJS)
    capabilityApisJS.loaded = new Promise(resolve => {
      capabilityApisJS.onload = () => { resolve() }
    })
    const capabilityApisCSS = document.createElement('link')
    capabilityApisCSS.href = `${(config.secure ? 'https://' : 'http://') + config.host + (config.port ? `:${config.port}` : '') + prefix}/resources/autogenerated/qlik-styles.css`
    capabilityApisCSS.type = 'text/css'
    capabilityApisCSS.rel = 'stylesheet'
    document.head.appendChild(capabilityApisCSS)
    capabilityApisCSS.loaded = new Promise(resolve => {
      capabilityApisCSS.onload = () => { resolve() }
    })

    capabilityApisPromise = Promise.all([capabilityApisJS.loaded, capabilityApisCSS.loaded])
    
    await capabilityApisPromise
  } catch (error) {
    throw new Error(error)
  }
}

function useCapability(config) {
  const [viz, setViz] = useState(() => {
    (async () => {
      if (config && config.qcs) {
        try {
          await loadCapSAAS(config)
          //const apps = await _request('/api/v1/items?limit=40', config).then(_deserialize);

          window.require.config({
            baseUrl: `https://${config.host}/resources`,
            webIntegrationId: config.webIntId,
          })
          const prefix = (config.prefix !== '') ? `/${config.prefix}/` : '/'

          return new Promise(resolve => {
            window.require(['js/qlik'], async q => {
              const app = q.openApp(config.appId, config)
              console.log(config)
              // apply theme set in QSE
          //    app.theme.get().then(theme => {
          //      theme.apply()
          //    })
              setViz(app)

              return 1
            })
          })
        } catch (error) {
          throw new Error(error)
        }

      } else {
        try {
          await loadCapabilityApis(config)
          const prefix = (config.prefix !== '') ? `/${config.prefix}/` : '/'
          window.require.config({
            baseUrl: `${(config.secure ? 'https://' : 'http://') + config.host + (config.port ? `:${config.port}` : '') + prefix}resources`,
            paths: {
              qlik: `${(config.secure ? 'https://' : 'http://') + config.host + (config.port ? `:${config.port}` : '') + prefix}resources/js/qlik`,
            },
            config: {
              text: {
                useXhr() {
                  return true
                },
              },
            },
          })

          return new Promise(resolve => {
            if (utility.globals.qlik) {
              const app = utility.globals.qlik.openApp(config.appId, { ...config, isSecure: config.secure, prefix })
              // apply theme set in QSE
              app.theme.get().then(theme => {
                theme.apply()
              })
              setViz(app)
            } else {
              window.require(['js/qlik'], q => {
                utility.globals.qlik = q
                utility.globals.resize = () => {
                  q.resize()
                }
                const app = q.openApp(config.appId, { ...config, isSecure: config.secure, prefix })
                setViz(app)

                return 1
              })
            }
          })
        } catch (error) {
          throw new Error(error)
        }
      }
    })()
  }, [])

  return { viz }
}

export default useCapability
